syntax = "proto3";
package telemetry;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/telemetry";

import "google/protobuf/timestamp.proto";

service HostMetrics {
  rpc Save(stream HostMetricsSample) returns (HostMetricsSaveResponse) {}
}

//////////////////////////////////////////

message HostMetricsSample {
  google.protobuf.Timestamp timestamp = 1;
  string host_id = 2;

  double cpu = 3;
  Memory memory = 4;
  Storage storage = 5;
  Network network = 6;


  message Memory {
    uint64 total = 1;
    uint64 used = 2;
  }

  message Storage {
    uint64 total = 1;
    uint64 used = 2;
  }

  message Network {
    double up_speed = 1;
    double down_speed = 2;
  }
}

message HostMetricsSaveResponse {
  uint64 saved_host_metrics = 1;
}
