syntax = "proto3";
package telemetry;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/telemetry";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

service LoadMetrics {
  rpc SaveSample(stream Sample) returns (SampleSaveResponse) {}
  rpc SaveTransaction(stream Transaction) returns (TransactionSaveResponse) {}
  rpc UpdateIterationCounters(IterationCounters) returns (google.protobuf.Empty) {}
}

//////////////////////////////////////////

message Sample {
  google.protobuf.Timestamp timestamp = 1;
  string host_id = 2;
  string synthetic_user_id = 3;

  google.protobuf.Duration duration = 4;

  string name = 5;
  uint64 sent_bytes = 6;
  uint64 received_bytes = 7;

  oneof sample_data {
    Rest rest = 100;
  }

  message Rest {
    string url = 1;
    string query_string = 2;
    string method = 3;
    bool is_redirect = 4;
    string final_url = 5;
  }
}

message SampleSaveResponse {
  uint64 saved_samples = 1;
}

//////////////////////////////////////////

message Transaction {
  string host_id = 1;
  string synthetic_user_id = 2;

  string name = 3;
  google.protobuf.Timestamp start = 4;
  google.protobuf.Timestamp end = 5;
  google.protobuf.Duration duration = 6;
  bool successful = 7;
}

message TransactionSaveResponse {
  uint64 saved_transactions = 1;
}

//////////////////////////////////////////

message IterationCounters {
  string host_id = 1;
  string synthetic_user_id = 2;

  uint64 completed = 3;
  uint64 in_progress = 4;
  uint64 passed = 5;
  uint64 failed = 6;
}