syntax = "proto3";
package injector;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/injector";

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";

service Agent {
  rpc Connect(ConnectRequest) returns (ConnectResponse) {}
  rpc Shutdown(ShutdownRequest) returns (google.protobuf.Empty) {}
  rpc Status(google.protobuf.Empty) returns (StatusResponse) {}
}

//////////////////////////////////////////

message ConnectRequest {
  string controller_version = 1;
  uint32 controller_port = 2;
}

message ConnectResponse {
  string injector_id = 1;
  string injector_version = 2;
}

//////////////////////////////////////////

message ShutdownRequest {
  bool forced = 1;
  google.protobuf.Duration timeout = 2;
}

//////////////////////////////////////////

message StatusResponse {
  Status status = 1;
}

enum Status {
  STARTING = 0;
  READY = 1;
  BUSY = 2;
  STOPPING = 3;
}