syntax = "proto3";
package injector;
option go_package = "github.com/steromano87/uzi/v1/pkg/injector";

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";

service Agent {
  rpc Handshake(Hello) returns (Welcome) {}
  rpc BeginSession(BeginSessionRequest) returns (google.protobuf.Empty) {}
  rpc EndSession(EndSessionRequest) returns (google.protobuf.Empty) {}
  rpc Shutdown(ShutdownRequest) returns (google.protobuf.Empty) {}
  rpc Status(google.protobuf.Empty) returns (StatusResponse) {}
}

//////////////////////////////////////////

message Hello {
  string controller_version = 1;
}

message Welcome {
  string injector_id = 1;
  string injector_version = 2;
}

//////////////////////////////////////////

message BeginSessionRequest {
  string name = 1;
  uint64 user_quota = 2;
  WorkspaceArchive archive = 3;
}

message WorkspaceArchive {
  bytes content = 1;
  CompressionAlgorithm compression_algorithm = 2;
}

enum CompressionAlgorithm {
  ZIP = 0;
}

//////////////////////////////////////////

message EndSessionRequest {
  string name = 1;
}

//////////////////////////////////////////

message ShutdownRequest {
  bool forced = 1;
  google.protobuf.Duration timeout = 2;
}

//////////////////////////////////////////

message StatusResponse {
  Status status = 1;
}

enum Status {
  STARTING = 0;
  READY = 1;
  BUSY = 2;
  STOPPING = 3;
}