syntax = "proto3";
package injector;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/injector";

import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

service Injector {
  rpc GetStatus(StatusRequest) returns (Status) {}
  rpc Acquire(stream HeartbeatRequest) returns (stream HeartbeatResponse) {}
  rpc Initialize(InitializationRequest) returns (google.protobuf.Empty) {}
  rpc SetRunnersQuota(RunnersQuota) returns (google.protobuf.Empty) {}
  rpc Shutdown(ShutdownRequest) returns (google.protobuf.Empty) {}
}

//////////////////////////////////////////

message StatusRequest {}

message Status {
  string version = 1;
  InjectorStatus status = 2;
  RunnerCounters runner_counters = 3;
}

message RunnerCounters {
  uint64 ready = 1;
  uint64 starting = 2;
  uint64 running = 3;
  uint64 stopping = 4;
  uint64 stopped = 5;
  uint64 error = 6;
}

//////////////////////////////////////////

message HeartbeatRequest {
  google.protobuf.Timestamp timestamp = 1;
}

message HeartbeatResponse {
  google.protobuf.Timestamp timestamp = 1;
}

//////////////////////////////////////////

message InitializationRequest {
  WorkingFolder working_folder = 1;
}

message WorkingFolder {
  bytes compressed_working_folder = 1;
  CompressionAlgorithm compression_algorithm = 2;
}

//////////////////////////////////////////

message RunnersQuota {
  uint64 quota = 1;
}

//////////////////////////////////////////

message ShutdownRequest {
  bool forced = 1;
  google.protobuf.Duration timeout = 2;
}

//////////////////////////////////////////

enum InjectorStatus {
  AVAILABLE = 0;
  ACQUIRED = 1;
  INITIALIZED = 2;
  ACTIVE = 3;
}

enum RunnerStatus {
  READY = 0;
  STARTING = 1;
  RUNNING = 2;
  STOPPING = 3;
  STOPPED = 4;
  ERROR = 5;
}

enum CompressionAlgorithm {
  ZIP = 0;
}