syntax = "proto3";
package injector;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/injector";

import "google/protobuf/duration.proto";
import "google/protobuf/empty.proto";

service Injector {
  rpc GetSyntheticUserCounters(SyntheticUserCountersRequest) returns (SyntheticUserCounters) {}
  rpc Initialize(InitializationRequest) returns (google.protobuf.Empty) {}
  rpc SetRunnersQuota(RunnersQuota) returns (google.protobuf.Empty) {}
  rpc Shutdown(ShutdownRequest) returns (google.protobuf.Empty) {}
}

//////////////////////////////////////////

message SyntheticUserCountersRequest {}

message SyntheticUserCounters {
  uint64 max_quota = 1;
  uint64 requested = 2;
  uint64 ready = 3;
  uint64 starting = 4;
  uint64 running = 5;
  uint64 stopping = 6;
  uint64 stopped = 7;
  uint64 error = 8;
}

//////////////////////////////////////////

message InitializationRequest {
  WorkingFolder working_folder = 1;
  uint64 max_users_quota = 2;
}

message WorkingFolder {
  bytes compressed_working_folder = 1;
  CompressionAlgorithm compression_algorithm = 2;
}

//////////////////////////////////////////

message RunnersQuota {
  uint64 quota = 1;
}

//////////////////////////////////////////

message ShutdownRequest {
  bool forced = 1;
  google.protobuf.Duration timeout = 2;
}

//////////////////////////////////////////

enum SyntheticUserStatus {
  READY = 0;
  STARTING = 1;
  RUNNING = 2;
  STOPPING = 3;
  STOPPED = 4;
  ERROR = 5;
}

enum CompressionAlgorithm {
  ZIP = 0;
}