name: My loading project with Harkonnen

harkonnenVersion: "all"

#################
# Configuration #
#################

injectors:
  localhost:
    local: true
    weight: 1

messaging:
  messageCapacity: 2048
  logging:
    bufferSize: 50
  samples:
    bufferSize: 10

logging:
  level: info

cockpit:
  scheduler:
    type: FixedInterval
    updateInterval: 2s

client:
  rest:
    timeout: 30s
    baseUrl: ""
    followRedirects: true
    keepCookies: true
    idleConnectionTimeout: 10s
    tlsHandshakeTimeout: 10s
    responseHeaderTimeout: 10s
    maxIdleConnections: 100
    maxConnectionsPerHost: 100
    maxIdleConnectionsPerHost: 100
    enableKeepAlive: true
    enableCompression: true

telemetry:
  hostMetrics:
    enabled: true
    pollInterval: 15s
    measureInterval: 250ms
