syntax = "proto3";
package workspace;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/workspace";

import "google/protobuf/empty.proto";

service Workspace {
  rpc Initialize(InitializationRequest) returns (InitializationResponse) {}
  rpc Reset(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

//////////////////////////////////////////

message InitializationRequest {
  bytes archive = 1;
  CompressionAlgorithm compression_algorithm = 2;
}

enum CompressionAlgorithm {
  ZIP = 0;
}

message InitializationResponse {
  string remote_working_folder = 1;
}
