syntax = "proto3";
package heartbeat;
option go_package = "github.com/steromano87/harkonnen/v1/pkg/injector/heartbeat";

import "google/protobuf/timestamp.proto";

service Heartbeat {
  rpc GetStatus(StatusRequest) returns (StatusResponse) {}
  rpc Lock(stream HeartbeatRequest) returns (stream HeartbeatResponse) {}
}

//////////////////////////////////////////

message StatusRequest {}

message StatusResponse {
  string version = 1;
  LockStatus status = 2;
}

enum LockStatus {
  AVAILABLE = 0;
  LOCKED = 1;
}

//////////////////////////////////////////

message HeartbeatRequest {
  google.protobuf.Timestamp timestamp = 1;
}

message HeartbeatResponse {
  google.protobuf.Timestamp timestamp = 1;
}