// Code generated by "stringer -type=Status"; DO NOT EDIT.

package syntheticuser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ready-0]
	_ = x[Starting-1]
	_ = x[Running-2]
	_ = x[Stopping-3]
	_ = x[Stopped-4]
	_ = x[Error-5]
}

const _Status_name = "ReadyStartingRunningStoppingStoppedError"

var _Status_index = [...]uint8{0, 5, 13, 20, 28, 35, 40}

func (i Status) String() string {
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return "Status(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
